version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - booknet

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - booknet

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - booknet

volumes:
  mongo_data:

networks:
  booknet:
